config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'relationships/show'
  get 'book_comments/create'
  get 'book_comments/destroy'
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  resources :books, only: [:index, :show, :edit, :update, :destroy, :create] do
   resource :book_comments,only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
 end
  resources :users, only: [:show, :index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

 belongs_to :user
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy

 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end

validates :title, presence: true
validates :body, presence: true
validates :body, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
   @book = Book.find(params[:book_id])
   BookComment.find_by(id: params[:id]).destroy
   redirect_to request.referer
  end

  private
  def book_comment_params
   params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all

  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    @user = @book.user
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
    render :index
    end
  end



  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @book_comment = BookComment.new
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  end

  def destroy
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  if @user != current_user
    redirect_to user_path(current_user)
  end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
       render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_error.html.erb
<% if book.errors.any? %>
<%= book.errors.count %>errors prohibited this obj from being saved:
<% book.errors.full_messages.each do |message| %>
 <%= message %>
<% end %>
<% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= render 'error', book: @book %>
<%= form_with model:@book, local: true do |f| %>
<p>Title</p>
<%= f.text_field :title %>
<p>Opinion</p>
<%= f.text_area :body %>
<%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show",book_path(@book.id) %>
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<%= render 'error', book: @book %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
<%= render 'users/sidebar', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
    <tr>

      <td><%= link_to user_path(book.user) do %>
      <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "60x60", fallback: "no_image.jpg" %>
      <% end %>
      </td>

      <td><%= link_to book.title,book_path(book.id) %></td>
      <td><%= book.body %></td>
      <% if book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(book), method: :delete do %>
        ♥<%= book.favorites.count %>
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(book), method: :post do %>
        ♡<%= book.favorites.count %>
      <% end %>
    </td>
     <% end %>
     <% end %>
     
    </tr>

  </tbody>
</table>
 </div>
 </div>
</div>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model:@book, local:true do |f| %>
<p>Title</p>
<%= f.text_field :title %>
<p>Opinion</p>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
<%= render 'users/sidebar', user: @user, book: @booknew %>
    </div>
    <div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
  <tr>
    <td><%= link_to user_path(@user) do %>
      <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', size: "60x60", fallback: "no_image.jpg" %><br>
      <%= @user.name %>
      <% end %>
      </td>
      <td><%= link_to @book.title,book_path(@book) %></td>
    <td><%= @book.body %></td>
      <% if @book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        ♥<%= @book.favorites.count %>
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(@book), method: :post do %>
        ♡<%= @book.favorites.count %>
      <% end %>
    </td>
    <td>
      コメント数:<%= @book.book_comments.count %>
    </td>
  <% end %>
    <% if @book.user == current_user %>
    <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
    <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか?",class: "btn btn-sm btn-danger" %></td>
    <% end %>
  </tr>
  <table>
  <tr>
  <% @book.book_comments.each do |book_comment| %>
  <td>
  <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', size: "60x60", fallback: "no_image.jpg" %><br>
  <%= book_comment.user.name %>
  </td>
  <td>
  <%= book_comment.comment %>

  </td>
  <td>
  <% if book_comment.user == current_user %>
  <%= link_to "Destroy", book_book_comments_path(book_comment.book, book_comment), method: :delete %>
  <% end %>
  </td>
  <% end %>
  </table>
  <div>
    <%= form_with model:[@book,@book_comment], local:true do |f| %>
    <%= f.text_area :comment %>
    <%= f.submit "送信" %>
    <% end %>
  </div>

</div>
</div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">

  <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>Bookers!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class= "row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-8">
    <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>

<p>in <i class="fas fa-book"></i><strong>Bookers</strong>,</br>
you can share and exchange your opinions ,
inpressions , and emotions</br>about various books!</p>

<div class="btn-wrapper col-10 mx-auto">

<%= link_to "Log in",new_user_session_path, class:  "btn btn-info btn-sm btn-block mb-3"%>
<%= link_to "Sign up",new_user_registration_path, class: "btn btn-success btn-sm btn-block"%>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/35d3da8b06.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light ">
        <div class="container">
      <a class="navbar-brand" href="/" >Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
    <li>
      <%= link_to " Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
    </li>
    <li>
      <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
    </li>
    <li>
      <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
    </li>
    <li>
      <%= link_to " Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
    </li>
    <% else %>
    <li>
      <%= link_to " Home", root_path, class: "nav-item text-light fas fa-home" %>
    </li>
    <li>
      <%= link_to " About",home_about_path, class: "nav-item text-light fas fa-link" %>
    </li>
    <li>
      <%= link_to " Sign up", new_user_registration_path, class: "nav-item text-light fas fa-user-plus" %>
    </li>
    <li>
      <%= link_to " Log in", new_user_session_path, class: "nav-item text-light fas fa-sign-in-alt" %>
    </li>
      <% end %>
      </ul>
      </div>
      </div>
      </nav>
    </header>
      <%= notice %>


    <%= yield %>


 <footer>
  <div class="container mt-5">
   <div class="row">
    <div class="mx-auto">
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
  </footer>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/show.html.erb
<h1>Relationships#show</h1>
<p>Find me in app/views/relationships/show.html.erb</p>

app/views/users/_sidebar.html.erb
<h2>User info</h2>
<table>
  <tr>
    <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "60x60", fallback: "no_image.jpg" %></td>
  </tr>
  <tr>
    <td>name <%= user.name %></td>
  </tr>
  <tr>
    <td>introduction <%= user.introduction %></td>
  </tr>
</table>
<% if user == current_user %>
 <p><%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>
 <% end %>

<h2>New book</h2>
<%= form_with model:book, local:true do |f| %>
<p>Title</p>
<%= f.text_field :title %>
<p>Opinion</p>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
<%= @user.errors.count %>errors prohibited this obj from being saved:
<% @user.errors.full_messages.each do |message| %>
 <%= message %>
<% end %>
<% end %>

<%= form_with model:@user, local:true do |f| %>
<label for="inputName">Name</label>
<%= f.text_field :name, autofocus: true, id:"inputName" %>
<label for="inputImage">Image</label>
<%= f.attachment_field :profile_image %>
<label for="inputIntroduction">Introduction</label>
<%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>

<%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/sidebar', user: @user, book: @book %>
     </div>
    <div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>

      <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show",user_path(user.id) %></td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <%= render 'sidebar', book: @book, user: @user %>
    </div>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
     <% @books.each do |book| %>
    <tr>

       <td><%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "60x60", fallback: "no_image.jpg" %>
        <% end %>
        </td>
      <td><%= link_to book.title,book_path(book.id) %></td>
      <td><%= book.body %></td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>